name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Acessar EC2 e fazer deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "ğŸ“ Acessando projeto"
            cd /home/${{ secrets.EC2_USER }}/projects/ssmai_project/ssmai-backend

            echo "ğŸ§¹ Limpando cache Docker"
            docker system prune -af
            docker volume prune -f

            echo "ğŸ”„ Atualizando repositÃ³rio"
            git fetch origin
            git reset --hard
            git clean -fd -e .env
            git checkout main
            git pull origin main

            echo "ğŸ§¨ Parando containers antigos"
            docker compose down --remove-orphans

            echo "ğŸ§± Buildando imagem sem cache"
            docker compose build --no-cache

            echo "ğŸš€ Subindo containers"
            docker compose up -d

            echo "ğŸ“œ Logs recentes do backend"
            docker compose logs --tail=50
